all:
	g++ -o first_prog first_prog.cpp -lopencv_imgcodecs -lopencv_core -lopencv_videoio -lopencv_video -lopencv_highgui -lopencv_imgproc
	g++ -o third_prog third_prog.cpp -lopencv_imgcodecs -lopencv_core -lopencv_videoio -lopencv_video -lopencv_highgui -lopencv_imgproc

clean:
	rm first_prog third_prog